name: Build
on:
  push:
    paths:
      - 'src/**'
      - '**.yml'
      - '**.xml'
      - '**.Dockerfile'
  pull_request:
    paths:
      - 'src/**'
      - '**.yml'
      - '**.xml'
      - '**.Dockerfile'
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        
        
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
